# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTBB_MVIjF0e2tNcK-1erT2WPdn3Tb0P
"""

!pip install -q keras_preprocessing


# ===========================
# Standard Libraries
# ===========================

import os  # Provides functions for interacting with the operating system
import re  # Regular expressions for string manipulation
from pathlib import Path  # Object-oriented file system paths
import shutil  # File operations such as copying and moving files

# TensorFlow Callbacks and Mixed Precision
from tensorflow.keras.callbacks import LambdaCallback  # Allows dynamic behavior during training
from tensorflow.keras import mixed_precision  # Enables mixed precision training
# mixed_precision.set_global_policy('mixed_float16')  # Uncomment to enable mixed precision (faster computation on supported hardware)

# ===========================
# Data Manipulation and Analysis
# ===========================

import pandas as pd  # Library for data analysis and manipulation
import numpy as np  # Numerical computations and array handling

# ===========================
# Data Visualization
# ===========================

import matplotlib.pyplot as plt  # Visualization library
import seaborn as sns  # Enhances Matplotlib with statistical plotting
from wordcloud import WordCloud, STOPWORDS  # For generating word clouds
from mlxtend.plotting import plot_confusion_matrix  # Function for plotting confusion matrices

# ===========================
# Deep Learning and TensorFlow
# ===========================

import tensorflow as tf  # Core deep learning library
from tensorflow.keras.layers import (  # Keras layers for deep learning models
    Concatenate, MultiHeadAttention, LayerNormalization,
    Dense, Input, Reshape, GlobalAvgPool2D, GlobalAvgPool1D,
    Conv1D, Add, Lambda, Layer
)
import keras.ops as K  # Keras operations module for mathematical functions

# Pretrained CNN Models
from tensorflow.keras.applications import VGG19  # Pretrained VGG19 model for image processing

# Keras Functional API for Model Creation
from tensorflow.keras.models import Model  # Keras model-building API

# Transformers (BERT)
from transformers import TFBertModel  # Pretrained BERT model for NLP tasks

# ===========================
# Machine Learning and Preprocessing
# ===========================

from sklearn import preprocessing  # Data preprocessing utilities
from sklearn.preprocessing import MinMaxScaler  # Feature scaling method
from sklearn.model_selection import train_test_split  # Splitting datasets into train/validation/test
from sklearn.utils import class_weight  # Handling imbalanced datasets

# Metrics for Model Evaluation
from sklearn.metrics import (
    classification_report,  # Generates detailed classification performance reports
    accuracy_score,  # Computes accuracy of predictions
    confusion_matrix,  # Generates a confusion matrix
    roc_auc_score,  # Computes ROC AUC score for classification
    average_precision_score  # Computes average precision for precision-recall curves
)

# ===========================
# Deep Learning - Keras & TensorFlow
# ===========================

import tensorflow as tf  # TensorFlow deep learning framework
from tensorflow import keras  # High-level deep learning API

# Keras Functional API for Building Models
from tensorflow.keras.models import Model  # Model-building API
from tensorflow.keras.layers import (  # Import additional layers
    MultiHeadAttention, LayerNormalization,
    Dense, Input, Reshape, Flatten
)
from tensorflow.keras.utils import to_categorical  # Converts labels to one-hot encoding

# ===========================
# Preprocessing for Images and Text
# ===========================

# Image Processing
from tensorflow.keras.preprocessing.image import ImageDataGenerator as keras_image  # Data augmentation and preprocessing for images

# Tokenization for Text Data
from tensorflow.keras.preprocessing.text import Tokenizer  # Tokenizer for converting text to sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences  # Use TensorFlow's version instead of keras_preprocessing

# Image Augmentation
from keras_preprocessing.image import ImageDataGenerator  # Data augmentation for training images

# ===========================
# NLP - Transformers (BERT)
# ===========================

from transformers import BertTokenizer, TFBertModel  # Pretrained BERT tokenizer and model for NLP tasks

# Print a confirmation message
print("All required libraries successfully imported.")

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/lidar/data/"

file_path1 = folder_path + 'data_clean (1).csv'
file_path2 = folder_path + 'clean_housing5.csv'
file_path3 = folder_path + 'sentiment.csv'
file_path4 = folder_path + 'all_data_reg.csv'

import pandas as pd
data_main = pd.read_csv(file_path1)
data_main2 = pd.read_csv(file_path2)
data2 = pd.read_csv(file_path3)
data = pd.read_csv(file_path4)

data_main.head()

data_main2.head()

data.head()

from sklearn.utils import resample

# Separate classes
df_majority = data[data['lbl'] == 0]
df_minority = data[data['lbl'] == 1]

# Downsample minority (lbl=1) by 10% fewer
new_minority_size = int(len(df_minority) * 0.5)
df_minority_downsampled = resample(
    df_minority,
    replace=False,             # sample without replacement
    n_samples=new_minority_size,
    random_state=42
)

# Combine majority and downsampled minority
df_downsampled = pd.concat([df_majority, df_minority_downsampled])

# Shuffle the dataset
df_downsampled = df_downsampled.sample(frac=1, random_state=42).reset_index(drop=True)

print("Original class counts:\n",data['lbl'].value_counts())
print("\nNew class counts after 10% downsampling of class 1:\n", df_downsampled['lbl'].value_counts())


####################################################3

#data=df_downsampled

# Count of each label
label_counts = data.lbl.value_counts()

# Frequency with percentage
label_freq = pd.DataFrame({
    'Count': label_counts,
    'Percentage': (label_counts / len(data.lbl) * 100).round(2)
})

print(label_freq)

"""# Rest of the code"""

# Preprocess data
import matplotlib.pyplot as plt  # Add this line to import matplotlib
import seaborn as sns # Import the seaborn library
import numpy as np # import numpy
from sklearn.preprocessing import MinMaxScaler # Make sure to import the MinMaxScaler class

data1 = data_main[['AR18', 'AR19']]
data1 = pd.get_dummies(data1, columns=data1.columns, drop_first=True)

# Merge datasets
merged_data = pd.concat([data2], axis=1)

# Create labels
data_main['lbl'] = data_main['AR166'].apply(lambda x: 0 if x == 0 else 1)

# Analyze class distribution
class_count = data_main["lbl"].value_counts().values
lst_class = data_main["lbl"].value_counts().index.to_list()
lst_class = ["class " + str(item) for item in lst_class]

# Map: class 1 -> nondefault, class 0 -> default
label_map = {'class 1': 'Non-default', 'class 0': 'Default', 1: 'nondefault', 0: 'default'}
labels_renamed = [label_map.get(lbl, lbl) for lbl in lst_class]

plt.figure(figsize=(6, 6))
palette_color = sns.color_palette('muted')
plt.pie(
    class_count,
    labels=labels_renamed,
    colors=palette_color,
    autopct='%.0f%%',
    textprops={'fontsize': 14}
)
plt.show()


# class 0 select
idx_class=np.argwhere(data_main['lbl'].values==0)
idx_class_0=[item[0] for item in idx_class]
idx_class_0=idx_class_0

# class 1 select
idx_class=np.argwhere(data_main['lbl'].values==1)
idx_class_1=[item[0] for item in idx_class]
idx_class_1=idx_class_1[0:14000]

# all select
idx_class_0.extend(idx_class_1)
data_main=data_main.iloc[idx_class_0]

merged_data=merged_data.iloc[idx_class_0]

# class 0 select
idx_class=np.argwhere(data_main2['lbl'].values==0)
idx_class_0=[item[0] for item in idx_class]
idx_class_0=idx_class_0

# class 1 select
idx_class=np.argwhere(data_main2['lbl'].values==1)
idx_class_1=[item[0] for item in idx_class]
#idx_class_1=idx_class_1[0:14000]

# all select
idx_class_0.extend(idx_class_1)
data_main2=data_main2.iloc[idx_class_0]

data_meta=merged_data

df_numeric=data_meta.values

scaler = MinMaxScaler()
scaler.fit(df_numeric)
df_numeric_normal = scaler.transform(df_numeric)

data_pre=data_main.copy()

im_size = (224,224)
input_size=(im_size[0],im_size[1],3)
batch_value=512

merged_data

import os

# Define paths
zip_file_path = "/content/drive/MyDrive/lidar/data/int.zip"  # Adjust if necessary
extract_folder = "data_image/first_class"

# Ensure the destination folder exists
os.makedirs(extract_folder, exist_ok=True)

import zipfile

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("Extraction complete!")

from pathlib import Path # Import the Path object from the pathlib module

folder_name = Path("data_image/first_class")
folder_name.mkdir(parents=True, exist_ok=True)  # Creates folder if it doesn't exist
print(f"Folder '{folder_name}' created successfully!")

# Define source directory (current directory) and destination folder
source_dir = Path("/content/drive/MyDrive/lidar/data/int/")  # Current directory
destination_folder = Path("data_image/first_class/")

# Ensure the destination folder exists
destination_folder.mkdir(parents=True, exist_ok=True)

# Move all .png files
for png_file in source_dir.glob("*.png"):
    shutil.move(str(png_file), str(destination_folder / png_file.name))
    print(f"Moved: {png_file} -> {destination_folder / png_file.name}")

print("All .png images have been moved successfully!")

import os

files = os.listdir(extract_folder)
print("Extracted files:", files)

!pip install -q keras_preprocessing # Re-install keras_preprocessing to ensure it's available in the current session
from tensorflow.keras.preprocessing.image import ImageDataGenerator as keras_image
from keras_preprocessing.image import ImageDataGenerator # This import should work after installation

import re

folder_name = Path("data_image/first_class")
folder_name.mkdir(parents=True, exist_ok=True)  # Creates folder if it doesn't exist
print(f"Folder '{folder_name}' created successfully!")

# Define source directory (current directory) and destination folder
source_dir = Path(".")  # Current directory
destination_folder = Path("data_image/first_class")

# Ensure the destination folder exists
destination_folder.mkdir(parents=True, exist_ok=True)

# Move all .png files
for png_file in source_dir.glob("*.png"):
    shutil.move(str(png_file), str(destination_folder / png_file.name))
    print(f"Moved: {png_file} -> {destination_folder / png_file.name}")

print("All .png images have been moved successfully!")

# Define the image directory path
image_path = 'data_image/'

# Initialize ImageDataGenerator for preprocessing images (rescaling pixel values)
image_generator = ImageDataGenerator(rescale=1./255)

# Load images from the directory, resizing them and setting batch size
image_set = image_generator.flow_from_directory(image_path,
                                                target_size=im_size,  # 'im_size' should be defined elsewhere
                                                batch_size=70295)  # Batch size should match dataset size

# Extract image data (X) and labels (y) from the dataset
X_image, y_image = image_set.__next__()

# Print the shape of the extracted image data
print(X_image.shape)

# Extract numerical indices from image filenames
# Handle cases where no numbers are found in filenames
idx_img = []
for item in image_set.filenames:
    matches = re.findall(r'\b\d+\b', item)
    if matches:  # Check if any matches were found
        idx_img.append(int(matches[0]))
    else:
        print(f"Warning: No numeric index found in filename: {item}")
        # Append a placeholder value (e.g., -1) or use some other logic
        idx_img.append(-1)

idx_img = np.array(idx_img)
idx_img.T  # Transpose the array (though not necessary here)

# Rename column 'AR129' to 'image name' in data_pre DataFrame
data_pre = data_pre.rename(columns={'AR129': 'image name'})

# Replace all occurrences of 0 in the 'image name' column with 10
data_pre.loc[data_pre["image name"] == 0, "image name"] = 10

# Initialize an empty list to store processed images
img_list = []

# Loop through image names in the dataset and extract corresponding images
for item in data_pre["image name"]:
    # Find indices where idx_img equals the current item
    matching_indices = np.where(idx_img == item)[0]
    if len(matching_indices) > 0:
        # Use the first matching index
        idx_im_find = matching_indices[0]
        img_list.append(X_image[idx_im_find].astype('float32'))  # Convert image to float16 and store
    else:
        # No matching image found, use a placeholder image (e.g., all zeros)
        print(f"Warning: No matching image found for 'image name' = {item}")
        placeholder_img = np.zeros(X_image[0].shape, dtype='float16')
        img_list.append(placeholder_img)

# Convert list to NumPy array
img_list = np.array(img_list)

# Extract text tokens from the dataset for word cloud visualization
data_token = data_pre["text_clean"].values
data_token2 = data_main2["text_clean"].values  # 'data_main2' should be defined earlier

# Generate and display a word cloud from the text data
from wordcloud import WordCloud, STOPWORDS  # Import WordCloud here
from tensorflow.keras.preprocessing.text import Tokenizer # Import Tokenizer here
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences here
from tensorflow.keras.utils import to_categorical # Import to_categorical
from sklearn.model_selection import train_test_split  # Make sure to import this function
import tensorflow.keras as keras # import the keras module under the alias 'keras'

# Generate and display a word cloud from the text data
plt.figure(figsize=(8, 8))
text = data_token
wordcloud = WordCloud().generate(str(text))

# Copy the tokenized text data
data_token_re = data_token.copy()

# Define the maximum number of words to keep in the tokenizer's vocabulary
MAX_NB_WORDS = 99826

# Initialize the tokenizer with the specified vocabulary size
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)

# Fit the tokenizer on the preprocessed text data
tokenizer.fit_on_texts(data_token_re)

# Convert the text data into sequences of numerical values
data_seq = tokenizer.texts_to_sequences(data_token_re)

# Calculate the vocabulary size (adding 1 because index 0 is reserved)
vocab_size = len(tokenizer.word_index) + 1

# Print the last preprocessed text entry and its corresponding sequence
print(data_token_re[-1])
print(data_seq[-1])

# Calculate the length of each sequence (number of words per entry)
frq_words = [len(item) for item in data_seq]

# Define the maximum sequence length (for padding)
maxlen = 500

# Ensure all sequences contain only integers and convert to numpy arrays
data_seq = [np.array([int(token) for token in seq], dtype=np.int32) for seq in data_seq]

# Pad sequences to ensure uniform length, truncating or padding with 0 as needed
data_seq_pad = pad_sequences(data_seq, padding='post', maxlen=maxlen, dtype=np.int32)

# Print the first 20 elements of the 10th padded sequence
print(data_seq_pad[10, 0:20])

# Convert labels to a binary format using one-hot encoding
lbl_binary = to_categorical(data_pre["lbl"].values).astype(int)

# Display the binary labels (optional)
lbl_binary

# Define the percentage of data to use for training
train_Percentage = 0.90

# Split the dataset into training (90%) and testing (10%) sets
x_train_text_split, x_test_text, lbl_train_split, lbl_test = train_test_split(
    data_seq_pad, lbl_binary, test_size=1 - train_Percentage, random_state=0,
    stratify=lbl_binary  # Ensure class balance is maintained
)

# Further split the training data into training (90%) and validation (10%) sets
x_train_text, x_valid_text, lbl_train, lbl_valid = train_test_split(
    x_train_text_split, lbl_train_split, test_size=1 - train_Percentage, random_state=0,
    stratify=lbl_train_split  # Ensure class balance is maintained
)

# Print the shapes of the training, validation, and test datasets along with their percentage of the total dataset
print('x_train shape: ', x_train_text.shape, np.round(x_train_text.shape[0] / data_pre.shape[0], 2), '%')
print('x_valid shape: ', x_valid_text.shape, np.round(x_valid_text.shape[0] / data_pre.shape[0], 2), '%')
print('x_test shape:  ', x_test_text.shape, np.round(x_test_text.shape[0] / data_pre.shape[0], 2), '%')

# Split the dataset into training (90%) and testing (10%) sets for image data
x_train_img_split, x_test_img, lbl_train_split, lbl_test = train_test_split(
    img_list,  # Image dataset
    lbl_binary,  # Corresponding labels
    test_size=1 - train_Percentage,  # Percentage of data used for testing
    random_state=0,  # Ensure reproducibility
    stratify=lbl_binary  # Ensure class balance is maintained
)

# Further split the training data into training (90%) and validation (10%) sets
x_train_img, x_valid_img, lbl_train, lbl_valid = train_test_split(
    x_train_img_split, lbl_train_split,
    test_size=1 - train_Percentage,  # Percentage of data used for validation
    random_state=0,  # Ensure reproducibility
    stratify=lbl_train_split  # Ensure class balance is maintained
)

# Print the shapes of the training, validation, and test datasets along with their percentage of the total dataset
print('x_train shape: ', x_train_img.shape, np.round(x_train_img.shape[0] / data_pre.shape[0], 2), '%')
print('x_valid shape: ', x_valid_img.shape, np.round(x_valid_img.shape[0] / data_pre.shape[0], 2), '%')
print('x_test shape:  ', x_test_img.shape, np.round(x_test_img.shape[0] / data_pre.shape[0], 2), '%')

# Split the dataset into training (90%) and testing (10%) sets for metadata
x_train_meta_split, x_test_meta, lbl_train_split, lbl_test = train_test_split(
    df_numeric_normal,  # Normalized numerical metadata
    lbl_binary,  # Corresponding labels
    test_size=1 - train_Percentage,  # Percentage of data used for testing
    random_state=0,  # Ensure reproducibility
    stratify=lbl_binary  # Ensure class balance is maintained
)

# Further split the training data into training (90%) and validation (10%) sets
x_train_meta, x_valid_meta, lbl_train, lbl_valid = train_test_split(
    x_train_meta_split, lbl_train_split,
    test_size=1 - train_Percentage,  # Percentage of data used for validation
    random_state=0,  # Ensure reproducibility
    stratify=lbl_train_split  # Ensure class balance is maintained
)

# Print the shapes of the training, validation, and test datasets along with their percentage of the total dataset
print('x_train shape: ', x_train_meta.shape, np.round(x_train_meta.shape[0] / data_pre.shape[0], 2), '%')
print('x_valid shape: ', x_valid_meta.shape, np.round(x_valid_meta.shape[0] / data_pre.shape[0], 2), '%')
print('x_test shape:  ', x_test_meta.shape, np.round(x_test_meta.shape[0] / data_pre.shape[0], 2), '%')

# Filter data_token2 to match the rows in data_pre before splitting
data_token2_filtered = data_main2.loc[data_pre.index, "text_clean"].values

# Split the dataset into training (90%) and testing (10%) sets for textual data
x_train_TEXT_split, x_test_TEXT, lbl_train_split, lbl_test = train_test_split(
    data_token,  # Tokenized text data
    lbl_binary,  # Corresponding labels
    test_size=1 - train_Percentage,  # Percentage of data used for testing
    random_state=0,  # Ensure reproducibility
    stratify=lbl_binary  # Ensure class balance is maintained
)

# Further split the training data into training (90%) and validation (10%) sets
x_train_TEXT, x_valid_TEXT, lbl_train, lbl_valid = train_test_split(
    x_train_TEXT_split, lbl_train_split,
    test_size=1 - train_Percentage,  # Percentage of data used for validation
    random_state=0,  # Ensure reproducibility
    stratify=lbl_train_split  # Ensure class balance is maintained
)

# Print the shapes of the training, validation, and test datasets along with their percentage of the total dataset
print('x_train shape: ', x_train_TEXT.shape, np.round(x_train_TEXT.shape[0] / data_pre.shape[0], 2), '%')
print('x_valid shape: ', x_valid_TEXT.shape, np.round(x_valid_TEXT.shape[0] / data_pre.shape[0], 2), '%')
print('x_test shape:  ', x_test_TEXT.shape, np.round(x_test_TEXT.shape[0] / data_pre.shape[0], 2), '%')

# Split the dataset into training (90%) and testing (10%) sets for the second textual dataset
x_train_TEXT_split2, x_test_TEXT2, lbl_train_split, lbl_test = train_test_split(
    data_token2_filtered,  # Filtered tokenized text data from a second dataset
    lbl_binary,  # Corresponding labels
    test_size=1 - train_Percentage,  # Percentage of data used for testing
    random_state=0,  # Ensure reproducibility
    stratify=lbl_binary  # Ensure class balance is maintained
)

# Further split the training data into training (90%) and validation (10%) sets
x_train_TEXT2, x_valid_TEXT2, lbl_train, lbl_valid = train_test_split(
    x_train_TEXT_split2, lbl_train_split,
    test_size=1 - train_Percentage,  # Percentage of data used for validation
    random_state=0,  # Ensure reproducibility
    stratify=lbl_train_split  # Ensure class balance is maintained
)

# Print the shapes of the training, validation, and test datasets along with their percentage of the total dataset
print('x_train shape: ', x_train_TEXT2.shape, np.round(x_train_TEXT2.shape[0] / data_pre.shape[0], 2), '%')
print('x_valid shape: ', x_valid_TEXT2.shape, np.round(x_valid_TEXT2.shape[0] / data_pre.shape[0], 2), '%')
print('x_test shape:  ', x_test_TEXT2.shape, np.round(x_test_TEXT2.shape[0] / data_pre.shape[0], 2), '%')

# Define evaluation metrics for the model
METRICS = [
    keras.metrics.TruePositives(name='tp'),  # Number of true positives
    keras.metrics.FalsePositives(name='fp'),  # Number of false positives
    keras.metrics.TrueNegatives(name='tn'),  # Number of true negatives
    keras.metrics.FalseNegatives(name='fn'),  # Number of false negatives
    keras.metrics.CategoricalAccuracy(name='accuracy'),  # Overall classification accuracy
    keras.metrics.Precision(name='precision'),  # Precision metric
    keras.metrics.Recall(name='recall'),  # Recall metric
    keras.metrics.AUC(name='auc'),  # Area under the ROC curve
    keras.metrics.AUC(name='prc', curve='PR')  # Area under the precision-recall curve
]

from sklearn.utils import class_weight # Make sure to import this module

from tensorflow.keras import layers, Model, Input




# Compute class weights for handling imbalanced data
class_weights_val = class_weight.compute_class_weight(
    class_weight='balanced',  # Balance class weights based on sample frequency
    classes=np.unique(np.argmax(lbl_valid, axis=1)),  # Unique class labels
    y=np.argmax(lbl_valid, axis=1)  # Convert one-hot labels to class indices
)

# Convert computed class weights into a dictionary format required by Keras
class_weight = dict()
for idx, val in enumerate(class_weights_val):
    class_weight[idx] = val  # Assign weight value to the corresponding class index

# Define the final image size with 3 color channels (RGB)
im_size_final = (im_size[0], im_size[1], 3)

# Print computed class weights and final image size for verification
print("Class Weights:", class_weight)
print("Final Image Size:", im_size_final)

!pip install transformers
from transformers import BertTokenizer, TFBertModel  # Import TFBertModel along with BertTokenizer

import tensorflow as tf # Import tensorflow here
from transformers import TFBertModel, AutoTokenizer

# Define key parameters
embedding_dim = 50  # Dimension of embedding layer (not used in BERT but might be useful for other models)
n_class = 2  # Number of output classes

# Define strategy for distributed training (useful for multi-GPU setups)
strategy = tf.distribute.MirroredStrategy()

# Create model and tokenizer within the distributed strategy scope
with strategy.scope():

    bert_layer = TFBertModel.from_pretrained(
        "bert-base-uncased",
        from_pt=True      # <- explicitly convert PT -> TF
    )

    tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=True)


def bert_encode(texts, tokenizer, max_len=512):

    # Ensure texts are properly converted to strings
    texts = [str(text) for text in texts]

    encoded = tokenizer(
        texts,
        max_length=max_len,  # Set maximum sequence length
        truncation=True,  # Truncate longer texts
        padding="max_length",  # Pad shorter texts to max_len
        return_tensors="tf",  # Return TensorFlow tensors
    )
    return {
        "input_ids": encoded["input_ids"],  # Token IDs
        "attention_mask": encoded["attention_mask"],  # Attention masks (1 for real tokens, 0 for padding)
        "token_type_ids": encoded["token_type_ids"],  # Segment IDs for sentence pairs (not always needed)
    }

# Print confirmation that BERT model and tokenizer are loaded
print("BERT model and tokenizer successfully loaded.")

# Use the same distributed training strategy
maxlen_bert = maxlen
with strategy.scope():
    # Encode the training text data using the BERT tokenizer
    train_input_bert = bert_encode(
        x_train_TEXT.tolist(),  # Convert text to a list of strings
        tokenizer,  # Use the pre-trained tokenizer
        max_len=maxlen_bert  # Define the maximum sequence length
    )

    # Encode the validation text data
    valid_input_bert = bert_encode(
        x_valid_TEXT.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the test text data
    test_input_bert = bert_encode(
        x_test_TEXT.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of training text data
    train_input_bert2 = bert_encode(
        x_train_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of validation text data
    valid_input_bert2 = bert_encode(
        x_valid_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of test text data
    test_input_bert2 = bert_encode(
        x_test_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

# Print confirmation message
print("BERT input encoding completed for training, validation, and test datasets.")

im_size_final=im_size[0],im_size[1],3

input_meta = Input(shape=(data_meta.shape[1], 1), name="browse_meta")

# Configure GPU memory growth
# gpus = tf.config.experimental.list_physical_devices('GPU')
# if gpus:
#     try:
#         for gpu in gpus:
#             tf.config.experimental.set_memory_growth(gpu, True)
#     except RuntimeError as e:
#         print(e)

# Custom BERT Layer (ignore PyTorch weight warnings)
class BertLayer(Layer):
    def __init__(self, model_name="bert-base-uncased", **kwargs):
        super().__init__(**kwargs)
        self.bert = TFBertModel.from_pretrained(model_name)

    def call(self, inputs):
        return self.bert(inputs).last_hidden_state[:, 0, :]  # CLS token





class BertLayer(layers.Layer):
    def __init__(self, bert_model: TFBertModel, trainable=False, **kwargs):
        super().__init__(**kwargs)
        self.bert = bert_model
        self.bert.trainable = trainable

    def call(self, input_ids):
        attn = tf.cast(input_ids > 0, tf.int32)
        token_type_ids = tf.zeros_like(input_ids)
        out = self.bert(
            input_ids=input_ids,
            attention_mask=attn,
            token_type_ids=token_type_ids,
            training=self.bert.trainable
        )
        return out.last_hidden_state[:, 0, :]  # CLS token

maxlen = int(train_input_bert['input_ids'].shape[1])
assert train_input_bert2['input_ids'].shape[1] == maxlen, "text1 and text2 must have same seq length"

from tensorflow.keras import layers
from tensorflow.keras.layers import (
    Input, Dense, Conv1D, Concatenate,
    GlobalAveragePooling1D, GlobalAveragePooling2D
)
from tensorflow.keras.models import Model
from tensorflow.keras.applications import VGG19
from transformers import TFBertModel
import tensorflow as tf


def _load_bert_backbone(model_name="bert-base-uncased"):
    """
    Robust loader for TFBertModel that avoids the safetensors iteration error.
    Tries native TF weights first, then falls back to converting PyTorch weights
    with use_safetensors=False.
    """
    try:
        # Prefer native TF weights
        return TFBertModel.from_pretrained(model_name, from_pt=False)
    except Exception as e1:
        try:
            # Fallback: convert PT -> TF, but disable safetensors to avoid the 'safe_open' error
            return TFBertModel.from_pretrained(model_name, from_pt=True, use_safetensors=False)
        except Exception as e2:
            raise RuntimeError(
                f"Failed to load TFBertModel. TF error: {e1}\nFallback (PT->TF) error: {e2}"
            )


class BertLayer(layers.Layer):
    def __init__(self, bert_model: TFBertModel, trainable=False, **kwargs):
        super().__init__(**kwargs)
        self.bert = bert_model
        self.bert.trainable = trainable

    def call(self, input_ids):
        # Build attention mask (pad tokens are 0)
        attn = tf.cast(input_ids > 0, tf.int32)
        token_type_ids = tf.zeros_like(input_ids)
        out = self.bert(
            input_ids=input_ids,
            attention_mask=attn,
            token_type_ids=token_type_ids,
            training=self.bert.trainable
        )
        # CLS token embedding
        return out.last_hidden_state[:, 0, :]


def multimodal_add_model(
    data_meta, maxlen, im_size, n_class=2,
    bert_backbone: TFBertModel | None = None,
    bert_trainable: bool = False,
    vgg_trainable: bool = False
):

    # ----- Inputs -----
    inp_meta = Input(shape=(data_meta.shape[1], 1), name="meta")
    inp_t1   = Input(shape=(maxlen,), dtype=tf.int32, name="text1_ids")
    inp_t2   = Input(shape=(maxlen,), dtype=tf.int32, name="text2_ids")
    inp_img  = Input(shape=im_size, name="image")

    # ----- BERT backbone (shared) -----
    if bert_backbone is None:
        bert_backbone = _load_bert_backbone()
    bert_layer = BertLayer(bert_backbone, trainable=bert_trainable, name="bert_encoder")

    t1_feat = bert_layer(inp_t1)                 # (batch, hidden)
    t1_feat = Dense(128, activation="relu", name="t1_fc")(t1_feat)

    t2_feat = bert_layer(inp_t2)                 # (batch, hidden)
    t2_feat = Dense(128, activation="relu", name="t2_fc")(t2_feat)

    # ----- Image encoder (VGG19) -----
    vgg = VGG19(include_top=False, weights="imagenet", input_shape=im_size, pooling=None)
    vgg.trainable = vgg_trainable
    img_feat = vgg(inp_img)                      # (batch, H', W', C')
    img_feat = GlobalAveragePooling2D(name="img_gap")(img_feat)
    img_feat = Dense(128, activation="relu", name="img_fc")(img_feat)

    # ----- Meta encoder -----
    meta_feat = Conv1D(32, kernel_size=2, activation="relu", name="meta_conv")(inp_meta)
    meta_feat = GlobalAveragePooling1D(name="meta_gap")(meta_feat)
    meta_feat = Dense(128, activation="relu", name="meta_fc")(meta_feat)

    # ----- Fusion -----
    fused = Add(name="add_fusion")([t1_feat, t2_feat, img_feat, meta_feat])
    x = Dense(128, activation="relu", name="fusion_fc")(fused)
    out = Dense(n_class, activation="softmax", name="final_softmax")(x)

    model = Model(
        inputs=[inp_meta, inp_t1, inp_t2, inp_img],
        outputs=out,
        name="MultiModalAddFusion"
    )
    return model


if __name__ == "__main__":
    # Minimal sanity check (shapes only). Replace with real data in your script.
    import numpy as np
    dummy_meta = np.zeros((10, 20))  # 20 meta features
    maxlen = 32
    im_size = (224, 224, 3)

    model = multimodal_add_model(dummy_meta, maxlen, im_size, n_class=2)
    model.summary()

model = multimodal_add_model(
    data_meta=data_meta,
    maxlen=maxlen_bert,                 # <-- now 500
    im_size=im_size_final,
    n_class=2,
    bert_trainable=False,
    vgg_trainable=False
)

from tensorflow.keras.utils import plot_model
plot_model(model, to_file="model_add.png", show_shapes=True, rankdir="LR")

maxlen

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC

def f1_macro_metric(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)  # <-- explicitly cast y_true
    y_pred_binary = tf.round(y_pred)

    tp = tf.reduce_sum(y_true * y_pred_binary, axis=0)
    fp = tf.reduce_sum((1 - y_true) * y_pred_binary, axis=0)
    fn = tf.reduce_sum(y_true * (1 - y_pred_binary), axis=0)

    precision = tp / (tp + fp + tf.keras.backend.epsilon())
    recall = tp / (tp + fn + tf.keras.backend.epsilon())
    f1 = 2 * precision * recall / (precision + recall + tf.keras.backend.epsilon())
    return tf.reduce_mean(f1)


model.compile(
    optimizer=Adam(learning_rate=3e-4, clipnorm=1.0),
    loss="categorical_crossentropy" if lbl_train.ndim == 2 else "sparse_categorical_crossentropy",
    metrics=[
        f1_macro_metric,
        AUC(curve='ROC', name='auc_roc', multi_label=True),
        AUC(curve='PR',  name='auc_pr',  multi_label=True),
        (tf.keras.metrics.CategoricalAccuracy(name='cat_acc')
         if lbl_train.ndim == 2
         else tf.keras.metrics.SparseCategoricalAccuracy(name='acc'))
    ],
)

# 4) Quick sanity on input shapes/dtypes
if x_train_meta.ndim == 2: x_train_meta = x_train_meta[..., None]
if x_valid_meta.ndim == 2: x_valid_meta = x_valid_meta[..., None]
train_input_bert['input_ids']  = tf.cast(train_input_bert['input_ids'], tf.int32)
train_input_bert2['input_ids'] = tf.cast(train_input_bert2['input_ids'], tf.int32)

# 5) Fit (unchanged)
train_inputs = [x_train_meta, train_input_bert['input_ids'], train_input_bert2['input_ids'], x_train_img]
valid_inputs = [x_valid_meta, valid_input_bert['input_ids'], valid_input_bert2['input_ids'], x_valid_img]
history = model.fit(
    x=train_inputs, y=lbl_train,
    validation_data=(valid_inputs, lbl_valid),
    epochs=100, batch_size=128,
    class_weight=class_weight, verbose=1
)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
out_dir = "/content/drive/MyDrive/mm_experiments/run_addition"
os.makedirs(out_dir, exist_ok=True)

import pandas as pd

hist_df = pd.DataFrame(history.history)
hist_path = f"{out_dir}/history.csv"
hist_df.to_csv(hist_path, index=False)
print("Saved:", hist_path)

import numpy as np
from sklearn.metrics import classification_report

y_true = np.argmax(lbl_valid, axis=1)
y_prob = model.predict(valid_inputs, batch_size=256, verbose=0)
y_pred = np.argmax(y_prob, axis=1)

report_dict = classification_report(y_true, y_pred, output_dict=True, zero_division=0)
report_df = pd.DataFrame(report_dict).transpose()
report_path = f"{out_dir}/classification_report.csv"
report_df.to_csv(report_path)
print("Saved:", report_path)

# Optionally also save raw predictions
preds_df = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "p_class0": y_prob[:,0],
    "p_class1": y_prob[:,1],
})
preds_path = f"{out_dir}/predictions.csv"
preds_df.to_csv(preds_path, index=False)
print("Saved:", preds_path)

model.save(f"{out_dir}/model_keras")





