# -*- coding: utf-8 -*-
"""capsule3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jajoY_09y11YQl4g2assfmxo4nLN9gV2
"""

!pip install -q keras_preprocessing


# ===========================
# Standard Libraries
# ===========================

import os  # Provides functions for interacting with the operating system
import re  # Regular expressions for string manipulation
from pathlib import Path  # Object-oriented file system paths
import shutil  # File operations such as copying and moving files

# TensorFlow Callbacks and Mixed Precision
from tensorflow.keras.callbacks import LambdaCallback  # Allows dynamic behavior during training
from tensorflow.keras import mixed_precision  # Enables mixed precision training
# mixed_precision.set_global_policy('mixed_float16')  # Uncomment to enable mixed precision (faster computation on supported hardware)

# ===========================
# Data Manipulation and Analysis
# ===========================

import pandas as pd  # Library for data analysis and manipulation
import numpy as np  # Numerical computations and array handling

# ===========================
# Data Visualization
# ===========================

import matplotlib.pyplot as plt  # Visualization library
import seaborn as sns  # Enhances Matplotlib with statistical plotting
from wordcloud import WordCloud, STOPWORDS  # For generating word clouds
from mlxtend.plotting import plot_confusion_matrix  # Function for plotting confusion matrices

# ===========================
# Deep Learning and TensorFlow
# ===========================

import tensorflow as tf  # Core deep learning library
from tensorflow.keras.layers import (  # Keras layers for deep learning models
    Concatenate, MultiHeadAttention, LayerNormalization,
    Dense, Input, Reshape, GlobalAvgPool2D, GlobalAvgPool1D,
    Conv1D, Add, Lambda, Layer
)
import keras.ops as K  # Keras operations module for mathematical functions

# Pretrained CNN Models
from tensorflow.keras.applications.vgg19 import VGG19, preprocess_input  # Pretrained VGG19 model for image processing

# Keras Functional API for Model Creation
from tensorflow.keras.models import Model  # Keras model-building API

# Transformers (BERT)
from transformers import TFBertModel  # Pretrained BERT model for NLP tasks

# ===========================
# Machine Learning and Preprocessing
# ===========================

from sklearn import preprocessing  # Data preprocessing utilities
from sklearn.preprocessing import MinMaxScaler  # Feature scaling method
from sklearn.model_selection import train_test_split  # Splitting datasets into train/validation/test
from sklearn.utils import class_weight  # Handling imbalanced datasets

# Metrics for Model Evaluation
from sklearn.metrics import (
    classification_report,  # Generates detailed classification performance reports
    accuracy_score,  # Computes accuracy of predictions
    confusion_matrix,  # Generates a confusion matrix
    roc_auc_score,  # Computes ROC AUC score for classification
    average_precision_score  # Computes average precision for precision-recall curves
)

# ===========================
# Deep Learning - Keras & TensorFlow
# ===========================

import tensorflow as tf  # TensorFlow deep learning framework
from tensorflow import keras  # High-level deep learning API

# Keras Functional API for Building Models
from tensorflow.keras.models import Model  # Model-building API
from tensorflow.keras.layers import (  # Import additional layers
    MultiHeadAttention, LayerNormalization,
    Dense, Input, Reshape, Flatten
)
from tensorflow.keras.utils import to_categorical  # Converts labels to one-hot encoding

# ===========================
# Preprocessing for Images and Text
# ===========================

# Image Processing
from tensorflow.keras.preprocessing.image import ImageDataGenerator as keras_image  # Data augmentation and preprocessing for images

# Tokenization for Text Data
from tensorflow.keras.preprocessing.text import Tokenizer  # Tokenizer for converting text to sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences  # Use TensorFlow's version instead of keras_preprocessing

# Image Augmentation
from keras_preprocessing.image import ImageDataGenerator  # Data augmentation for training images

# ===========================
# NLP - Transformers (BERT)
# ===========================

from transformers import BertTokenizer, TFBertModel  # Pretrained BERT tokenizer and model for NLP tasks

# Print a confirmation message
print("All required libraries successfully imported.")

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/lidar/data/"

file_path1 = folder_path + 'data_clean (1).csv'
file_path2 = folder_path + 'clean_housing5.csv'
file_path3 = folder_path + 'sentiment.csv'
file_path4 = folder_path + 'all_data_reg.csv'

import pandas as pd
data_main = pd.read_csv(file_path1)
data_main2 = pd.read_csv(file_path2)
data2 = pd.read_csv(file_path3)
data = pd.read_csv(file_path4)

data_main.head()

data_main2.head()

data.head()

from sklearn.utils import resample

# Separate classes
df_majority = data[data['lbl'] == 0]
df_minority = data[data['lbl'] == 1]

# Downsample minority (lbl=1) by 10% fewer
new_minority_size = int(len(df_minority) * 0.5)
df_minority_downsampled = resample(
    df_minority,
    replace=False,             # sample without replacement
    n_samples=new_minority_size,
    random_state=42
)

# Combine majority and downsampled minority
df_downsampled = pd.concat([df_majority, df_minority_downsampled])

# Shuffle the dataset
df_downsampled = df_downsampled.sample(frac=1, random_state=42).reset_index(drop=True)

print("Original class counts:\n",data['lbl'].value_counts())
print("\nNew class counts after 10% downsampling of class 1:\n", df_downsampled['lbl'].value_counts())


####################################################3

data=df_downsampled

# Count of each label
label_counts = data.lbl.value_counts()

# Frequency with percentage
label_freq = pd.DataFrame({
    'Count': label_counts,
    'Percentage': (label_counts / len(data.lbl) * 100).round(2)
})

print(label_freq)

"""# Rest of the code"""

# Preprocess data
import matplotlib.pyplot as plt  # Add this line to import matplotlib
import seaborn as sns # Import the seaborn library
import numpy as np # import numpy
from sklearn.preprocessing import MinMaxScaler # Make sure to import the MinMaxScaler class

data1 = data_main[['AR18', 'AR19']]
data1 = pd.get_dummies(data1, columns=data1.columns, drop_first=True)

# Merge datasets
merged_data = pd.concat([data2], axis=1)

# Create labels
data_main['lbl'] = data_main['AR166'].apply(lambda x: 0 if x == 0 else 1)

# Analyze class distribution
class_count = data_main["lbl"].value_counts().values
lst_class = data_main["lbl"].value_counts().index.to_list()
lst_class = ["class " + str(item) for item in lst_class]

# Plot class distribution
plt.figure(figsize=(6, 6))
palette_color = sns.color_palette('muted')
plt.pie(
    class_count,
    labels=lst_class,
    colors=palette_color,
    autopct='%.0f%%',
    textprops={'fontsize': 14}
)
plt.title('Number of each class')
plt.show()

# class 0 select
idx_class=np.argwhere(data_main['lbl'].values==0)
idx_class_0=[item[0] for item in idx_class]
idx_class_0=idx_class_0

# class 1 select
idx_class=np.argwhere(data_main['lbl'].values==1)
idx_class_1=[item[0] for item in idx_class]
idx_class_1=idx_class_1[0:14000]

# all select
idx_class_0.extend(idx_class_1)
data_main=data_main.iloc[idx_class_0]

merged_data=merged_data.iloc[idx_class_0]

# class 0 select
idx_class=np.argwhere(data_main2['lbl'].values==0)
idx_class_0=[item[0] for item in idx_class]
idx_class_0=idx_class_0

# class 1 select
idx_class=np.argwhere(data_main2['lbl'].values==1)
idx_class_1=[item[0] for item in idx_class]
idx_class_1=idx_class_1[0:14000]

# all select
idx_class_0.extend(idx_class_1)
data_main2=data_main2.iloc[idx_class_0]

data_meta=merged_data

df_numeric=data_meta.values

scaler = MinMaxScaler()
scaler.fit(df_numeric)
df_numeric_normal = scaler.transform(df_numeric)

data_pre=data_main.copy()

im_size = (224,224)
input_size=(im_size[0],im_size[1],3)
batch_value=512

merged_data

import os

# Define paths
zip_file_path = "/content/drive/MyDrive/lidar/data/int.zip"  # Adjust if necessary
extract_folder = "data_image/first_class"

# Ensure the destination folder exists
os.makedirs(extract_folder, exist_ok=True)

import zipfile

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("Extraction complete!")

from pathlib import Path # Import the Path object from the pathlib module

folder_name = Path("data_image/first_class")
folder_name.mkdir(parents=True, exist_ok=True)  # Creates folder if it doesn't exist
print(f"Folder '{folder_name}' created successfully!")

# Define source directory (current directory) and destination folder
source_dir = Path("/content/drive/MyDrive/lidar/data/int/")  # Current directory
destination_folder = Path("data_image/first_class/")

# Ensure the destination folder exists
destination_folder.mkdir(parents=True, exist_ok=True)

# Move all .png files
for png_file in source_dir.glob("*.png"):
    shutil.move(str(png_file), str(destination_folder / png_file.name))
    print(f"Moved: {png_file} -> {destination_folder / png_file.name}")

print("All .png images have been moved successfully!")

import os

files = os.listdir(extract_folder)
print("Extracted files:", files)

!pip install -q keras_preprocessing # Re-install keras_preprocessing to ensure it's available in the current session
from tensorflow.keras.preprocessing.image import ImageDataGenerator as keras_image
from keras_preprocessing.image import ImageDataGenerator # This import should work after installation

import re

folder_name = Path("data_image/first_class")
folder_name.mkdir(parents=True, exist_ok=True)  # Creates folder if it doesn't exist
print(f"Folder '{folder_name}' created successfully!")

# Define source directory (current directory) and destination folder
source_dir = Path(".")  # Current directory
destination_folder = Path("data_image/first_class")

# Ensure the destination folder exists
destination_folder.mkdir(parents=True, exist_ok=True)

# Move all .png files
for png_file in source_dir.glob("*.png"):
    shutil.move(str(png_file), str(destination_folder / png_file.name))
    print(f"Moved: {png_file} -> {destination_folder / png_file.name}")

print("All .png images have been moved successfully!")

# Define the image directory path
image_path = 'data_image/'

# Initialize ImageDataGenerator for preprocessing images (rescaling pixel values)
image_generator = ImageDataGenerator(rescale=1./255)

# Load images from the directory, resizing them and setting batch size
image_set = image_generator.flow_from_directory(image_path,
                                                target_size=im_size,  # 'im_size' should be defined elsewhere
                                                batch_size=70295)  # Batch size should match dataset size

# Extract image data (X) and labels (y) from the dataset
X_image, y_image = image_set.__next__()

# Print the shape of the extracted image data
print(X_image.shape)

# Extract numerical indices from image filenames
# Handle cases where no numbers are found in filenames
idx_img = []
for item in image_set.filenames:
    matches = re.findall(r'\b\d+\b', item)
    if matches:  # Check if any matches were found
        idx_img.append(int(matches[0]))
    else:
        print(f"Warning: No numeric index found in filename: {item}")
        # Append a placeholder value (e.g., -1) or use some other logic
        idx_img.append(-1)

idx_img = np.array(idx_img)
idx_img.T  # Transpose the array (though not necessary here)

# Rename column 'AR129' to 'image name' in data_pre DataFrame
data_pre = data_pre.rename(columns={'AR129': 'image name'})

# Replace all occurrences of 0 in the 'image name' column with 10
data_pre["image name"][data_pre["image name"] == 0] = 10

# Initialize an empty list to store processed images
img_list = []

# Loop through image names in the dataset and extract corresponding images
for item in data_pre["image name"]:
    # Find indices where idx_img equals the current item
    matching_indices = np.where(idx_img == item)[0]
    if len(matching_indices) > 0:
        # Use the first matching index
        idx_im_find = matching_indices[0]
        img_list.append(X_image[idx_im_find].astype('float32'))  # Convert image to float16 and store
    else:
        # No matching image found, use a placeholder image (e.g., all zeros)
        print(f"Warning: No matching image found for 'image name' = {item}")
        placeholder_img = np.zeros(X_image[0].shape, dtype='float32')
        img_list.append(placeholder_img)

# Convert list to NumPy array
img_list = np.array(img_list)

# Extract text tokens from the dataset for word cloud visualization
data_token = data_pre["text_clean"].values
data_token2 = data_main2["text_clean"].values  # 'data_main2' should be defined earlier

# Generate and display a word cloud from the text data
from wordcloud import WordCloud, STOPWORDS  # Import WordCloud here
from tensorflow.keras.preprocessing.text import Tokenizer # Import Tokenizer here
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences here
from tensorflow.keras.utils import to_categorical # Import to_categorical
from sklearn.model_selection import train_test_split  # Make sure to import this function
import tensorflow.keras as keras # import the keras module under the alias 'keras'

# Generate and display a word cloud from the text data
plt.figure(figsize=(8, 8))
text = data_token
wordcloud = WordCloud().generate(str(text))

# Copy the tokenized text data
data_token_re = data_token.copy()

# Define the maximum number of words to keep in the tokenizer's vocabulary
MAX_NB_WORDS = 99826

# Initialize the tokenizer with the specified vocabulary size
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)

# Fit the tokenizer on the preprocessed text data
tokenizer.fit_on_texts(data_token_re)

# Convert the text data into sequences of numerical values
data_seq = tokenizer.texts_to_sequences(data_token_re)

# Calculate the vocabulary size (adding 1 because index 0 is reserved)
vocab_size = len(tokenizer.word_index) + 1

# Print the last preprocessed text entry and its corresponding sequence
print(data_token_re[-1])
print(data_seq[-1])

# Calculate the length of each sequence (number of words per entry)
frq_words = [len(item) for item in data_seq]

# Define the maximum sequence length (for padding)
maxlen = 256

# Ensure all sequences contain only integers and convert to numpy arrays
data_seq = [np.array([int(token) for token in seq], dtype=np.int32) for seq in data_seq]

# Pad sequences to ensure uniform length, truncating or padding with 0 as needed
data_seq_pad = pad_sequences(data_seq, padding='post', maxlen=maxlen, dtype=np.int32)

# Print the first 20 elements of the 10th padded sequence
print(data_seq_pad[10, 0:20])

# Convert labels to a binary format using one-hot encoding
lbl_binary = to_categorical(data_pre["lbl"].values).astype(int)
# === Unified split across modalities (consistent indices; scaler on train only) ===

# 1) Choose a single length for *all* text inputs
#    Use a data-driven heuristic: 95th percentile across both text sources
import numpy as np

def seq_len_list(texts, tokenizer):
    # Cheap length estimator without full batching; OK for sizing
    # Use texts_to_sequences for Keras Tokenizer
    return [len(seq) for seq in tokenizer.texts_to_sequences(texts)]


lens1 = seq_len_list(data_token, tokenizer)   # your first text channel (raw)
lens2 = seq_len_list(data_token2, tokenizer)  # your second text channel (raw)

p95 = int(np.percentile(lens1 + lens2, 95))
# Clamp to reasonable bounds (BERT limit is 512)
maxlen = max(128, min(512, p95))
maxlen_bert = maxlen

print(f"Chosen maxlen={maxlen} (95th percentile of sequence lengths)")

# --- Unified splits ONLY (no more per-modality re-splits) ---

# If you still want to peek at lbl_binary, keep it—but don't re-split anything
_ = lbl_binary
_idx_all = np.arange(len(lbl_binary))
_y_all = np.argmax(lbl_binary, axis=1)

import os, numpy as np, tensorflow as tf
from sklearn.model_selection import train_test_split as _tts

# Determinism first (safe fallbacks if TF version differs)
os.environ["PYTHONHASHSEED"] = "1337"
np.random.seed(1337)
tf.random.set_seed(1337)
try:
    tf.config.experimental.enable_op_determinism()
except Exception:
    os.environ["TF_DETERMINISTIC_OPS"] = "1"

_idx_all = np.arange(len(lbl_binary))
_y_all   = np.argmax(lbl_binary, axis=1)

# 10% test, 20% validation (of TOTAL). To get 20% valid from remaining 90% train:
_valid_frac_total = 0.20
_valid_frac_within_train = _valid_frac_total / (1.0 - 0.10)  # ≈ 0.2222

train_idx, test_idx  = _tts(_idx_all, test_size=0.10, random_state=1337, stratify=_y_all)
train_idx, valid_idx = _tts(train_idx,  test_size=_valid_frac_within_train,
                            random_state=1337, stratify=_y_all[train_idx])

# Raw text for BERT encoders
x_train_TEXT = data_token[train_idx]
x_valid_TEXT = data_token[valid_idx]
x_test_TEXT  = data_token[test_idx]

x_train_TEXT2 = data_token2[train_idx]
x_valid_TEXT2 = data_token2[valid_idx]
x_test_TEXT2  = data_token2[test_idx]

# Images
import numpy as _np
img_list = _np.array(img_list).astype('float32')/255.0
x_train_img = img_list[train_idx]
x_valid_img = img_list[valid_idx]
x_test_img  = img_list[test_idx]

# Meta / numeric (scale on train only)
from sklearn.preprocessing import MinMaxScaler as _MMS
df_numeric = data_meta.values
_scaler = _MMS().fit(df_numeric[train_idx])
x_train_meta = _scaler.transform(df_numeric[train_idx])[..., None]
x_valid_meta = _scaler.transform(df_numeric[valid_idx])[..., None]
x_test_meta  = _scaler.transform(df_numeric[test_idx])[..., None]

# Labels
lbl_train = lbl_binary[train_idx]
lbl_valid = lbl_binary[valid_idx]
lbl_test  = lbl_binary[test_idx]

# Text (padded) channel aligned by the same indices
x_train_text = data_seq_pad[train_idx]
x_valid_text = data_seq_pad[valid_idx]
x_test_text  = data_seq_pad[test_idx]

# (Optional) simple shape/percentage report for one channel
n_total = data_seq_pad.shape[0]
pct = lambda arr: np.round(arr.shape[0] / n_total, 2)
print('x_train_text shape:', x_train_text.shape, pct(x_train_text), '%')
print('x_valid_text shape:', x_valid_text.shape, pct(x_valid_text), '%')
print('x_test_text  shape:', x_test_text.shape,  pct(x_test_text),  '%')

# --- Final alignment sanity checks across ALL modalities/labels ---
def _same_len(*xs):
    return len(set([x.shape[0] for x in xs])) == 1

assert _same_len(x_train_meta, x_train_img, x_train_text, x_train_TEXT, x_train_TEXT2, lbl_train), "TRAIN sets misaligned"
assert _same_len(x_valid_meta, x_valid_img, x_valid_text, x_valid_TEXT, x_valid_TEXT2, lbl_valid), "VALID sets misaligned"
assert _same_len(x_test_meta,  x_test_img,  x_test_text,  x_test_TEXT,  x_test_TEXT2,  lbl_test),  "TEST sets misaligned"

print("OK: all modalities are aligned (train/valid/test).")

METRICS = [
    keras.metrics.TruePositives(name='tp'),  # Number of true positives
    keras.metrics.FalsePositives(name='fp'),  # Number of false positives
    keras.metrics.TrueNegatives(name='tn'),  # Number of true negatives
    keras.metrics.FalseNegatives(name='fn'),  # Number of false negatives
    keras.metrics.CategoricalAccuracy(name='accuracy'),  # Overall classification accuracy
    keras.metrics.Precision(name='precision'),  # Precision metric
    keras.metrics.Recall(name='recall'),  # Recall metric
    keras.metrics.AUC(name='auc'),  # Area under the ROC curve
    keras.metrics.AUC(name='prc', curve='PR')  # Area under the precision-recall curve
]

from sklearn.utils import class_weight # Make sure to import this module





# Compute class weights for handling imbalanced data
class_weights_val = class_weight.compute_class_weight(
    class_weight='balanced',  # Balance class weights based on sample frequency
    classes=np.unique(np.argmax(lbl_train, axis=1)),  # Unique class labels
    y=np.argmax(lbl_train, axis=1)  # Convert one-hot labels to class indices
)

# Convert computed class weights into a dictionary format required by Keras
class_weight_dict = {}
for idx, val in enumerate(class_weights_val):
    class_weight_dict[idx] = val  # Assign weight value to the corresponding class index

# Define the final image size with 3 color channels (RGB)
im_size_final = (im_size[0], im_size[1], 3)

# Print computed class weights and final image size for verification
print("Class Weights:", class_weight)
print("Final Image Size:", im_size_final)

!pip install transformers
from transformers import BertTokenizer, TFBertModel  # Import TFBertModel along with BertTokenizer

import tensorflow as tf # Import tensorflow here
from transformers import TFBertModel, AutoTokenizer

# Define key parameters
embedding_dim = 50  # Dimension of embedding layer (not used in BERT but might be useful for other models)
n_class = 2  # Number of output classes

# Define strategy for distributed training (useful for multi-GPU setups)
strategy = tf.distribute.MirroredStrategy()

# Create model and tokenizer within the distributed strategy scope
with strategy.scope():

    bert_layer = TFBertModel.from_pretrained(
        "bert-base-uncased",
        from_pt=True      # <- explicitly convert PT -> TF
    )

    tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=True)


def bert_encode(texts, tokenizer, max_len=512):

    # Ensure texts are properly converted to strings
    texts = [str(text) for text in texts]

    encoded = tokenizer(
        texts,
        max_length=max_len,  # Set maximum sequence length
        truncation=True,  # Truncate longer texts
        padding="max_length",  # Pad shorter texts to max_len
        return_tensors="tf",  # Return TensorFlow tensors
    )
    return {
        "input_ids": encoded["input_ids"],  # Token IDs
        "attention_mask": encoded["attention_mask"],  # Attention masks (1 for real tokens, 0 for padding)
        "token_type_ids": encoded["token_type_ids"],  # Segment IDs for sentence pairs (not always needed)
    }

# Print confirmation that BERT model and tokenizer are loaded
print("BERT model and tokenizer successfully loaded.")




# Use the same distributed training strategy
maxlen_bert = maxlen
with strategy.scope():
    # Encode the training text data using the BERT tokenizer
    train_input_bert = bert_encode(
        x_train_TEXT.tolist(),  # Convert text to a list of strings
        tokenizer,  # Use the pre-trained tokenizer
        max_len=maxlen_bert  # Define the maximum sequence length
    )

    # Encode the validation text data
    valid_input_bert = bert_encode(
        x_valid_TEXT.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the test text data
    test_input_bert = bert_encode(
        x_test_TEXT.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of training text data
    train_input_bert2 = bert_encode(
        x_train_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of validation text data
    valid_input_bert2 = bert_encode(
        x_valid_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

    # Encode the second set of test text data
    test_input_bert2 = bert_encode(
        x_test_TEXT2.tolist(),
        tokenizer,
        max_len=maxlen_bert
    )

# Print confirmation message
print("BERT input encoding completed for training, validation, and test datasets.")

im_size_final=im_size[0],im_size[1],3

input_meta = Input(shape=(data_meta.shape[1], 1), name="browse_meta")

# Configure GPU memory growth
# gpus = tf.config.experimental.list_physical_devices('GPU')
# if gpus:
#     try:
#         for gpu in gpus:
#             tf.config.experimental.set_memory_growth(gpu, True)
#     except RuntimeError as e:
#         print(e)

# Custom BERT Layer (ignore PyTorch weight warnings)
class BertLayer(Layer):
    def __init__(self, model_name="bert-base-uncased", **kwargs):
        super().__init__(**kwargs)
        self.bert = TFBertModel.from_pretrained(model_name)

    def call(self, inputs):
        return self.bert(inputs).last_hidden_state[:, 0, :]  # CLS token

# Assume BertLayer is defined/imported elsewhere:
# from your_bert_module import BertLayer
from tensorflow.keras import layers, Model, Input

# --------------------------------------------
# 1) squash non-linearity for capsules
# --------------------------------------------
def squash(vectors, axis=-1, epsilon=1e-7):
    s2 = tf.reduce_sum(tf.square(vectors), axis=axis, keepdims=True)
    scale = s2 / (1. + s2) / tf.sqrt(s2 + epsilon)
    return scale * vectors

# --------------------------------------------
# 2) Primary capsule layers
# --------------------------------------------
class PrimaryCapDense(layers.Layer):
    def __init__(self, num_caps, dim_caps, **kwargs):
        super().__init__(**kwargs)
        self.num_caps = num_caps
        self.dim_caps = dim_caps
        self.dense = layers.Dense(num_caps * dim_caps, activation='elu')

    def call(self, inputs):
        x = self.dense(inputs)  # [batch, num_caps * dim_caps]
        batch = tf.shape(x)[0]
        x = tf.reshape(x, (batch, self.num_caps, self.dim_caps))
        return squash(x)

class PrimaryCapConv2D(layers.Layer):
    def __init__(self, num_caps, dim_caps, kernel_size, strides, **kwargs):
        super().__init__(**kwargs)
        self.num_caps = num_caps
        self.dim_caps = dim_caps
        self.conv = layers.Conv2D(
            filters=num_caps * dim_caps,
            kernel_size=kernel_size,
            strides=strides,
            padding="valid",
            activation='elu'
        )

    def call(self, inputs):
        x = self.conv(inputs)  # [batch, h, w, num_caps * dim_caps]
        batch = tf.shape(x)[0]
        h, w = tf.shape(x)[1], tf.shape(x)[2]
        x = tf.reshape(x, (batch, h * w * self.num_caps, self.dim_caps))
        return squash(x)

# --------------------------------------------
# 3) DigitCaps: dynamic routing
# --------------------------------------------
class DigitCaps(layers.Layer):
    def __init__(self, n_caps, dim_caps, routings=3, **kwargs):
        super().__init__(**kwargs)
        self.n_caps = n_caps
        self.dim_caps = dim_caps
        self.routings = routings

    def build(self, input_shape):
        in_caps, in_dim = input_shape[1], input_shape[2]
        # weight matrix for routing: [in_caps, n_caps, in_dim, dim_caps]
        self.W = self.add_weight(
            shape=(in_caps, self.n_caps, in_dim, self.dim_caps),
            initializer="glorot_uniform",
            trainable=True
        )

    def call(self, inputs):
        # inputs: [batch, in_caps, in_dim]
        batch = tf.shape(inputs)[0]
        u = tf.expand_dims(inputs, 2)              # [batch, in_caps, 1, in_dim]
        u = tf.tile(u, [1, 1, self.n_caps, 1])     # [batch, in_caps, n_caps, in_dim]
        u_hat = tf.einsum("bijd,ijdh->bijh", u, self.W)

        b_ij = tf.zeros_like(u_hat[..., 0])        # [batch, in_caps, n_caps]
        for i in range(self.routings):
            c_ij = tf.nn.softmax(b_ij, axis=-1)
            s_j = tf.reduce_sum(tf.expand_dims(c_ij, -1) * u_hat, axis=1)
            v_j = squash(s_j)                     # [batch, n_caps, dim_caps]
            if i < self.routings - 1:
                agreement = tf.reduce_sum(
                    u_hat * tf.expand_dims(v_j, 1), axis=-1
                )
                b_ij += agreement
        return v_j  # [batch, n_caps, dim_caps]

# --------------------------------------------
# 4) Per-modality metric layers
# --------------------------------------------
class CosineSimMetric(layers.Layer):
    def __init__(self, n_class, dim_caps, **kwargs):
        super().__init__(**kwargs)
        self.n_class = n_class
        self.dim_caps = dim_caps

    def build(self, _):
        self.class_emb = self.add_weight(
            shape=(self.n_class, self.dim_caps),
            initializer="glorot_uniform",
            trainable=True
        )

    def call(self, caps_out):
        # caps_out: [batch, n_class, dim_caps]
        z_norm = tf.linalg.l2_normalize(caps_out, axis=-1)
        e_norm = tf.linalg.l2_normalize(self.class_emb, axis=-1)
        cos = tf.einsum("bcd,cd->bc", z_norm, e_norm)
        return (cos + 1.0) / 2.0  # [batch, n_class]

class SquashNormMetric(layers.Layer):
    def call(self, caps_out):
        return tf.norm(caps_out, axis=-1)  # [batch, n_class]

class SoftmaxNegEntropyPerClass(layers.Layer):
    def call(self, caps_out):
        # caps_out: [batch, n_class, dim_caps]
        # 1) capsule lengths → [batch, n_class]
        lengths = tf.norm(caps_out, axis=-1)
        # 2) softmax to get p → [batch, n_class]
        p = tf.nn.softmax(lengths, axis=-1)
        # 3) per-class neg‐entropy term: −p_i·log₂(p_i) → [batch, n_class]
        neg_ent = -p * tf.math.log(p + 1e-8) / tf.math.log(2.0)
        # 4) (optionally) shift by +1 if you want  in [1,1+…] rather than [0,…]
        scores = 1.0 + neg_ent
        return scores  # shape = [batch, n_class]

from tensorflow.keras import layers

class BertLayer(layers.Layer):
    def __init__(self, bert_model: TFBertModel, trainable=False, **kwargs):
        super().__init__(**kwargs)
        self.bert = bert_model
        self.bert.trainable = trainable

    def call(self, input_ids):
        attn = tf.cast(input_ids > 0, tf.int32)
        token_type_ids = tf.zeros_like(input_ids)
        out = self.bert(
            input_ids=input_ids,
            attention_mask=attn,
            token_type_ids=token_type_ids,
            training=self.bert.trainable
        )
        return out.last_hidden_state[:, 0, :]  # CLS token
bert_layer_wrapped = BertLayer(bert_layer, trainable=False)

def build_multimodal_capsule_model(
    data_meta,
    maxlen,
    im_size,
    n_class=2,
    routing_iters=3
):
    # Inputs
    inp_meta = Input(shape=(data_meta.shape[1], 1), name="meta")
    inp_t1   = Input(shape=(maxlen,), dtype=tf.int32, name="text1")
    inp_t2   = Input(shape=(maxlen,), dtype=tf.int32, name="text2")
    inp_img  = Input(shape=im_size, name="image")

    # ----- Text Branch (Cosine Similarity between two texts) -----
   # e1 = BertLayer()(inp_t1)  # [batch, embed_dim]
   # e2 = BertLayer()(inp_t2)  # [batch, embed_dim]


    e1 = bert_layer_wrapped(inp_t1)
    e2 = bert_layer_wrapped(inp_t2)

    # Capsule encoding for each text separately
    pc_t1 = PrimaryCapDense(6, 8)(e1)
    dc_t1 = DigitCaps(1, 16, routings=routing_iters)(pc_t1)  # Single capsule

    pc_t2 = PrimaryCapDense(6, 8)(e2)
    dc_t2 = DigitCaps(1, 16, routings=routing_iters)(pc_t2)  # Single capsule

    # Flatten capsules for similarity
    caps_t1 = layers.Flatten()(dc_t1)  # [batch, 16]
    caps_t2 = layers.Flatten()(dc_t2)  # [batch, 16]

    # Custom Layer for safe cosine similarity
    class SafeCosineSimilarity(layers.Layer):
        def call(self, inputs):
            x1, x2 = inputs
            x1 = tf.where(tf.equal(tf.norm(x1, axis=-1, keepdims=True), 0.0), x1 + 1e-6, x1)
            x2 = tf.where(tf.equal(tf.norm(x2, axis=-1, keepdims=True), 0.0), x2 + 1e-6, x2)
            return tf.reduce_sum(tf.linalg.l2_normalize(x1, axis=-1) * tf.linalg.l2_normalize(x2, axis=-1), axis=-1, keepdims=True)

    # Cosine similarity explicitly
    txt_similarity = SafeCosineSimilarity(name="cosine_safe")([caps_t1, caps_t2])  # [batch, 1]
    txt_similarity_proj = layers.Dense(n_class, activation='elu', name="txt_sim_projection")(txt_similarity)


    # ----- Image Branch -----
    x_img = layers.Lambda(lambda z: preprocess_input(z))(inp_img)
    _vgg = VGG19(include_top=False, weights="imagenet")
    _vgg.trainable = False

    for layer in _vgg.layers:
      layer.trainable = ("block5" in layer.name)  # only fine-tune the top block

    v = _vgg(x_img)
    pc_img = PrimaryCapConv2D(32, 8, kernel_size=3, strides=2)(v)
    dc_img = DigitCaps(n_class, 16, routings=routing_iters)(pc_img)
    score_img = SquashNormMetric()(dc_img)            # [batch, n_class]

    # ----- Numeric (Meta) Branch -----
    nm = layers.Conv1D(32, 2, activation="relu")(inp_meta)
    nm = layers.Flatten()(nm)

    # Custom Layer for safe norm on numeric data
    class SafeNormNumeric(layers.Layer):
        def call(self, inputs):
            return tf.where(tf.equal(tf.norm(inputs, axis=-1, keepdims=True), 0.0), inputs + 1e-6, inputs)

    nm = SafeNormNumeric()(nm)
    pc_num = PrimaryCapDense(16, 8)(nm)
    dc_num = DigitCaps(n_class, 16, routings=routing_iters)(pc_num)
    score_num = SoftmaxNegEntropyPerClass()(dc_num)   # [batch, n_class]

    # ----- After Metrics Computation -----

    # Assume each metric outputs shape [batch, 2]
    # e.g., txt_similarity_proj, score_img, score_num all have [batch, 2]

    # Apply learnable weights W1, W2, W3 to each modality explicitly
    weighted_txt = layers.Dense(2, activation="linear", use_bias=False, name="W_txt")(txt_similarity_proj)
    weighted_img = layers.Dense(2, activation="linear", use_bias=False, name="W_img")(score_img)
    weighted_num = layers.Dense(2, activation="linear", use_bias=False, name="W_num")(score_num)

    # Concatenate weighted features explicitly
    concat_features = layers.Concatenate(axis=-1, name="concat_weighted_features")(
        [weighted_txt, weighted_img, weighted_num]  # shape: [batch, 6]
    )

    x = layers.BatchNormalization()(concat_features)
    x = layers.Dropout(0.15)(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.15)(x)
    out = layers.Dense(n_class, activation="tanh", name="final")(x)


    # Final Model
    return Model(
        inputs=[inp_meta, inp_t1, inp_t2, inp_img],
        outputs=out,
        name="MultiModalCapsule"
    )

# Instantiate the model
model = build_multimodal_capsule_model(
    data_meta, maxlen, im_size_final, n_class=2, routing_iters=3
)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.utils import plot_model


plot_model(
     model,
     to_file="model.png",
     show_shapes=True,
     show_layer_names=True,
     rankdir="LR")      # left‑to‑right layout

!pip install -U tensorflow-addons

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC, Precision, Recall
from tensorflow.keras.callbacks import EarlyStopping

import tensorflow as tf
from tensorflow.keras.metrics import AUC, Precision, Recall
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.metrics import AUC, Precision, Recall


def f1_macro(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)  # <-- explicitly cast y_true
    y_pred_binary = tf.round(y_pred)

    tp = tf.reduce_sum(y_true * y_pred_binary, axis=0)
    fp = tf.reduce_sum((1 - y_true) * y_pred_binary, axis=0)
    fn = tf.reduce_sum(y_true * (1 - y_pred_binary), axis=0)

    precision = tp / (tp + fp + tf.keras.backend.epsilon())
    recall = tp / (tp + fn + tf.keras.backend.epsilon())
    f1 = 2 * precision * recall / (precision + recall + tf.keras.backend.epsilon())
    return tf.reduce_mean(f1)

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC, Precision, Recall

# Use a named metric so history has a predictable key
# f1_macro_metric defined later (tfa fallback)
model.compile(
    optimizer=Adam(learning_rate=3e-4, clipnorm=1.0),
    loss="categorical_crossentropy",
    metrics=[f1_macro,
             AUC(curve='ROC', name="auc_roc"),
             AUC(curve='PR',  name="auc_pr")]
)



# 2) Prepare your inputs exactly as before
train_inputs = [
    x_train_meta,
    train_input_bert['input_ids'],
    train_input_bert2['input_ids'],
    x_train_img
]
valid_inputs = [
    x_valid_meta,
    valid_input_bert['input_ids'],
    valid_input_bert2['input_ids'],
    x_valid_img
]

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
callbacks = [
    ReduceLROnPlateau(mode='max', monitor="val_auc_pr", factor=0.5, patience=4, min_lr=1e-6, verbose=1),
    EarlyStopping(mode='max', monitor="val_auc_pr", patience=10, restore_best_weights=True, min_delta=1e-4, verbose=1),
    ModelCheckpoint(
    "best_kmodel.weights.h5",
    monitor="val_auc_pr",
    mode="max",
    save_best_only=True,
    save_weights_only=True,
    verbose=0
),
]




# replace categorical_crossentropy with a smoothed version
loss = tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05)
model.compile(optimizer=Adam(learning_rate=2e-4, clipnorm=1.0),
              loss=loss,
              metrics=[f1_macro,
                      AUC(curve='ROC', name="auc_roc"),
                      AUC(curve='PR',  name="auc_pr")])



#######################################NEW
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint


callbacks = [
    ReduceLROnPlateau(mode='max', monitor="val_auc_pr", factor=0.5, patience=3, min_lr=1e-6, verbose=1),
    EarlyStopping(mode='max', monitor="val_auc_pr", patience=12, restore_best_weights=True, min_delta=5e-4, verbose=1),
    ModelCheckpoint("best_kmodel.weights.h5", monitor="val_auc_pr", mode="max", save_best_only=True, save_weights_only=True),
]



###############################

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers.schedules import CosineDecayRestarts

# Cosine with small restarts for exploration; tweak initial_learning_rate if needed
steps_per_epoch = int(np.ceil(lbl_train.shape[0] / 256))
lr_schedule = CosineDecayRestarts(
    initial_learning_rate=3e-4,
    first_decay_steps=steps_per_epoch * 6,  # ~6 epochs per cycle
    t_mul=1.5,
    m_mul=0.8,
    alpha=1e-6
)

opt = keras.optimizers.Adam(learning_rate=lr_schedule, clipnorm=1.0)
model.compile(optimizer=opt,
              loss=loss,
              metrics=[f1_macro,
                      AUC(curve='ROC', name="auc_roc"),
                      AUC(curve='PR',  name="auc_pr")])

callbacks = [
    EarlyStopping(mode='max', monitor="val_auc_pr", patience=15,
                  restore_best_weights=True, min_delta=7.5e-4, verbose=1),
    ModelCheckpoint("best_kmodel.weights.h5", monitor="val_auc_pr", mode="max",
                    save_best_only=True, save_weights_only=True),
]


from tensorflow.keras.callbacks import ModelCheckpoint  # (Remove EarlyStopping import)

callbacks = [
    ModelCheckpoint("best_kmodel.weights.h5",
                    monitor="val_auc_pr", mode="max",
                    save_best_only=True, save_weights_only=True),
]

# 3) Fit
history = model.fit(
    x=train_inputs,
    y=lbl_train,
    validation_data=(valid_inputs, lbl_valid),
    epochs=100,                # or however many you like
    batch_size=128,
    class_weight=class_weight_dict,
    verbose=1,
    callbacks=callbacks,

)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os
out_dir = "/content/drive/MyDrive/mm_experiments/run_cap3"
os.makedirs(out_dir, exist_ok=True)

import pandas as pd

hist_df = pd.DataFrame(history.history)
hist_path = f"{out_dir}/history.csv"
hist_df.to_csv(hist_path, index=False)
print("Saved:", hist_path)

import numpy as np
from sklearn.metrics import classification_report

y_true = np.argmax(lbl_valid, axis=1)
y_prob = model.predict(valid_inputs, batch_size=256, verbose=0)
y_pred = np.argmax(y_prob, axis=1)

report_dict = classification_report(y_true, y_pred, output_dict=True, zero_division=0)
report_df = pd.DataFrame(report_dict).transpose()
report_path = f"{out_dir}/classification_report.csv"
report_df.to_csv(report_path)
print("Saved:", report_path)

# Optionally also save raw predictions
preds_df = pd.DataFrame({
    "y_true": y_true,
    "y_pred": y_pred,
    "p_class0": y_prob[:,0],
    "p_class1": y_prob[:,1],
})
preds_path = f"{out_dir}/predictions.csv"
preds_df.to_csv(preds_path, index=False)
print("Saved:", preds_path)

model.save(f"{out_dir}/model_keras")

